import sympy
a,b=map(int,input().split())
c,d=map(int,input().split())
e,f=map(int,input().split())
x,y,m,n=sympy.symbols('x y m n')
e1=sympy.Eq(x+y,a)
e2=sympy.Eq(m+n,b)
e3=sympy.Eq(x+m,c)
e4=sympy.Eq(y+n,d)
e5=sympy.Eq(x+n,e)
e6=sympy.Eq(y+m,f)
s=sympy.solve((e1,e2,e3,e4,e5,e6),(x,y,m,n))
print(s[x], s[y])
print(s[m], s[n])
